MohammadWaleed/keycloak-admin-client

- README.md
- src/Resources/Definitions/keycloak-1_0.php
- src/Resources/keycloak-1_0.php
README: Added ToC, fixe, added links
Added new file (Definitions) for the API
Added new API (getClientRoleUsers)
> Update to v0.2.0

- README.md
- src/Admin/KeycloakClient.php
- src/Admin/Resources/keycloak-1_0.php
Add support for Client Initial Access APIs
Add support for Client Registration Policy API
> Add support for new APIs

- README.md
- src/Admin/Classes/FullBodyLocation.php
- src/Admin/KeycloakClient.php
- src/Admin/Resources/keycloak-1_0.php
added new location (fullBody location) that will add the parameter as is to the body without the keys
add support for Client Role Mapping APIs
> Add new location and API support

- README.md
- src/Admin/KeycloakClient.php
- src/Admin/Resources/keycloak-1_0.php
Hello,
I added 2 new methods to the client and updated the documentation:
- addUserToGroup (use user id and group id to assign a user to a group)
- deleteUserFromGroup (user user id and group id to remove a user from a group)
PS: nice package btw, keep up the good work !
> Added user assignment to groups and updated doc

- README.md
- composer.json
- src/Admin/KeycloakClient.php
- src/Admin/Resources/keycloak-1_0.php
* Added addUserToGroup and deleteUserFromGroup  by @vcreuza 
* Added Guzzle 7 support
* Add support for Roles (by ID) APIs
> Add support for Roles (by ID) APIs, package upgrades, and other api supports

- src/Admin/Classes/FullBodyLocation.php
* fixes issue while adding fullbody parameters that were being deleted
before sending request to keycloak server, ie, body was empty
> fix: fullbody location

- README.md
- src/Admin/KeycloakClient.php
- src/Admin/Resources/keycloak-1_0.php
* feat: add partial update for keycloak user data
* added updatePartialUser config to user http method PATCH instead of
PUT
- PUT removes settings that are not present in json
- PATCH only updates data sent in json
* feat: add partial update for keycloak user data
* updated README.md with new method
Co-authored-by: Mohammad Waleed <mohammed.barghash99@gmail.com>
Co-authored-by: Cristina Nunes <cristina@sbin.pt>
> Feature: patch update user (#38)

- README.md
- src/Admin/KeycloakClient.php
- src/Admin/Resources/keycloak-1_0.php
* Added support client credentials grant type @mega 
* Added support for users reset password API by @syffer
> Add new features

- README.md
- src/Admin/KeycloakClient.php
- src/Admin/Resources/keycloak-1_0.php
* Add ability to pass custom middleware @syffer 
* Add new API support (User count) @syffer
> Custom Middleware and new API support

- README.md
- src/Admin/KeycloakClient.php
- src/Admin/Resources/keycloak-1_0.php
This PR is very important for me, and the developer that started this PR does not respond, so here we go.
> Feature execute actions email

- README.md
- src/Admin/Classes/FullBodyLocation.php
- src/Admin/KeycloakClient.php
- src/Admin/Middleware/RefreshToken.php
- src/Admin/Resources/keycloak-1_0.php
- src/Admin/TokenStorages/ChainedTokenStorage.php
- src/Admin/TokenStorages/RuntimeTokenStorage.php
- src/Admin/TokenStorages/TokenStorage.php
* Added execue actions email api support by @mrdj07 
* Added token storage customization by @syffer 
* Added support for client secret instead of password @syffer
> prepare v0.23.0

- src/Admin/Middleware/RefreshToken.php
Currently, the token is retrieved synchronously.
When the keycloak server is restarted, it loses the previous token it has generated, and will not be able to recognize the previous token used by the library.
When that happens, as the token is retrieved synchronously, the guzzle client throws an exception before entering the guzzle handler, and so the token stored is never reinitialized.
In order to sole this, the token can be retrieved asynchronously, by using a promise, which will be returned as a handler.
> Use a promise to retrieve the token

- README.md
* add missing parameters on getUserCount by @Gwemox
> Prepare for 0.27.0

- src/Admin/Resources/keycloak-1_0.php
* Add exact parameter for getUsers endpoint by @t-atanasoski
> prepare for 0.28.0

- src/Admin/KeycloakClient.php
- src/Admin/Resources/keycloak-1_0.php
add trigger functions (tested and working fine)
> add syncUserStorage

- src/Admin/KeycloakClient.php
- src/Admin/Resources/keycloak-1_0.php
* add syncUserStorage by @igittigitt
* make it possible to extend the KeycloakClient by @dgoosens
> prepare for 0.29.0

- README.md
- src/Admin/Middleware/RefreshToken.php
- src/Admin/Resources/keycloak-1_0.php
https://github.com/MohammadWaleed/keycloak-admin-client/issues/84
> Remove auth/ in the base URL

- README.md
- src/Admin/KeycloakClient.php
- src/Admin/Middleware/RefreshToken.php
- src/Admin/Resources/keycloak-1_0.php
* Remove auth/ in the base URL by @funkycram
> prepare for 0.30.0

- README.md
- src/Admin/KeycloakClient.php
- src/Admin/Resources/keycloak-1_0.php
Tested, the new "getUserSessions" method works.
> Add getUserSessions method

- src/Admin/Resources/keycloak-1_0.php
https://www.keycloak.org/docs-api/17.0/rest-api/index.html#_users_resource
> Add q parameter to getUsers method

- README.md
- src/Admin/KeycloakClient.php
- src/Admin/Middleware/RefreshToken.php
- src/Admin/Resources/keycloak-1_0.php
* Removed duplicated method definition by @funkycram 
* Add getUserSessions method by @funkycram 
* Add q parameter to getUsers method  by @dobro-lubov
> prepare for 0.31.0

- README.md
- src/Admin/KeycloakClient.php
- src/Admin/Resources/keycloak-1_0.php
* Add functions for socialLoginProviders by @foliengriller
> prepare for 0.32.0

- README.md
- src/Admin/KeycloakClient.php
- src/Admin/Resources/keycloak-1_0.php
* Fixed service definition of createChildGroup, remove name clash of id by @micbis 
* Add functions to get user consents by @foliengriller
> prepare for 0.33.0

- README.md
- src/Admin/KeycloakClient.php
- src/Admin/Resources/keycloak-1_0.php
* Add functions to get user credentials by @foliengriller
> prepare for 0.34.0

- README.md
- src/Admin/KeycloakClient.php
- src/Admin/Resources/keycloak-1_0.php
HTTP PATCH is not supported by keycloak
So this does not work.
> Removes function "updatePartialUser"

- README.md
- src/Admin/KeycloakClient.php
- src/Admin/Resources/keycloak-1_0.php
* https://github.com/MohammadWaleed/keycloak-admin-client/pull/102 by @foliengriller 
* https://github.com/MohammadWaleed/keycloak-admin-client/pull/103 by @xhezairbey
> prepare for 0.35.0

- src/Admin/KeycloakClient.php
> rename api version config key to not interfer with http protocol version

- README.md
> Adds trailing slash to auth-example

- src/Admin/Resources/keycloak-1_0.php
Allow reserved characters in the uri in group by path query
> Support for raw uri's (i.e. to query for groups by path)

- README.md
- src/Admin/KeycloakClient.php
- src/Admin/Resources/keycloak-1_0.php
I was missing the possibility to get all realms. Please consider adding this to your repo.
> Add getRealms to access all visible Realms

- README.md
- src/Admin/Classes/FullTextLocation.php
- src/Admin/KeycloakClient.php
- src/Admin/Resources/keycloak-1_0.php
* Hotfix - Typo in FullTextLocation by @tafhyseni 
* Add missing "attributes" parameter for getGroups, getUserCount and getClients by @jphooiveld
* Adds trailing slash to auth-example by @foliengriller 
* Allow reserved uri characters in group by path query by @thomome
* Support for raw uri's (i.e. to query for groups by path) by @micbis
* Added getGroupChildren & deleteUserCredential functions by @micbis
* Add getRealms to access all visible Realms by @PhilippKolmann
> prepare for 0.38.0
